tok: IDENTIFIER [words]
tok: IDENTIFIER [snake_case]
tok: IDENTIFIER [CamelCase]
tok: IDENTIFIER [middle_0123_numbers]
tok: IDENTIFIER [emphatic!]
tok: IDENTIFIER [inquisitive?]
tok: IDENTIFIER [counted0]
tok: NEWLINE [\n]
