tok: STRING ["simple double-quoted"]
tok: NEWLINE [\n]
tok: STRING ['simple single-quotes']
tok: NEWLINE [\n]
tok: STRING ["double-quoted with \" internal"]
tok: NEWLINE [\n]
tok: STRING ['single-quoted with \' internal']
tok: NEWLINE [\n]
tok: STRINGSTART ["the answer is #{]
tok: INTEGER [6]
tok: MULTLIKE [*]
tok: INTEGER [7]
tok: STRINGEND [}"]
tok: NEWLINE [\n]
tok: STRINGSTART ["multiple #{]
tok: INTEGER [1]
tok: STRINGMID [} interpolations #{]
tok: TVAR [%foo]
tok: STRINGEND [} inside"]
tok: NEWLINE [\n]
tok: STRINGSTART ["this #{]
tok: STRINGSTART ["is #{]
tok: STRING ['crazy']
tok: STRINGMID [} but #{]
tok: STRING ["someone"]
tok: STRINGEND [}"]
tok: STRINGEND [} could do it"]
tok: NEWLINE [\n]
