tok: SYMBOL [:bareword]
tok: NEWLINE [\n]
tok: QUOTEDSYMBOL [:"double"]
tok: NEWLINE [\n]
tok: QUOTEDSYMBOL [:'single']
tok: NEWLINE [\n]
tok: SYMBOLSTART [:"inter #{]
tok: INTEGER [3]
tok: PLUSLIKE [+]
tok: INTEGER [4]
tok: STRINGEND [} polated"]
tok: NEWLINE [\n]
