tok: SYMBOL [bareword]
tok: NEWLINE [\n]
tok: SYMBOL [double]
tok: NEWLINE [\n]
tok: SYMBOL [single]
tok: NEWLINE [\n]
tok: SYMBOLSTART [inter]
tok: INTEGER [3]
tok: PLUSLIKE [+]
tok: INTEGER [4]
tok: STRINGEND [ polated]
tok: NEWLINE [\n]
