#!/bin/sh
#
# Bootstrap a reasonable development environment, using the packaging utility for the current platform.

has () {
  which $1 >/dev/null 2>&1
  return $?
}

if has brew; then
  brew install ragel lemon icu4c
fi

if has apt-get; then
  sudo apt-get install ragel lemon libicu-dev
fi

