#!/bin/bash
set -e
rm -f ./core
clear

INFILE=${1:-default.seg}

ulimit -c unlimited
echo -e ">> building >>>>>>>>>>>>>>>>>\n"
make clean bin/segment DEBUG=1
echo -e "\n>> executing >>>>>>>>>>>>>>>>\n"

set +e
bin/segment --lexer-debug --ast-debug --verbose ${INFILE}
EXITCODE=$?
set -e

if [ -e core ]; then
  echo -e "\n>> stack >>>>>>>>>>>>>>>>>>>>\n"
  gdb --batch --eval-command=bt bin/segment ./core
else
  echo -e "\n>> exited with ${EXITCODE} >>>>>>>>>>>>\n"
fi

if [ -z ${KEEP_CORE} ]; then
  rm -f ./core
fi
