#!/bin/bash
set -e
rm -f ./core
clear

case $1 in
  unit)
    UNIT=1
    ;;
  *)
    ;;
esac

INFILE=${1:-default.seg}

ulimit -c unlimited
echo -e ">> building >>>>>>>>>>>>>>>>>\n"
make clean bin/segment DEBUG=1
echo -e "\n>> executing >>>>>>>>>>>>>>>>\n"

set +e
if [ -z $UNIT ]; then
  EXECUTABLE=bin/segment
  ${EXECUTABLE} --debug lexer --debug ast --debug symbol --verbose ${INFILE}
  EXITCODE=$?
else
  EXECUTABLE=tests/suite
  make test DEBUG=1
  EXITCODE=$?
fi
set -e

if [ -e core ]; then
  echo -e "\n>> stack >>>>>>>>>>>>>>>>>>>>\n"
  gdb --batch --eval-command=bt ${EXECUTABLE} ./core
else
  echo -e "\n>> exited with ${EXITCODE} >>>>>>>>>>>>\n"
fi

if [ -z ${KEEP_CORE} ]; then
  rm -f ./core
fi
